<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLf2urbc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLf2urbc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLf2urbc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLf2urbc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLf2urbc\appProdProjectContainer([
    'container.build_hash' => 'Lf2urbc',
    'container.build_id' => 'd82d9f60',
    'container.build_time' => 1612443656,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLf2urbc');
