<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKbnx2md\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKbnx2md/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKbnx2md.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKbnx2md\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKbnx2md\appProdProjectContainer([
    'container.build_hash' => 'Kbnx2md',
    'container.build_id' => '30ec259e',
    'container.build_time' => 1608469546,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKbnx2md');
